version: '2'

services:
  database:
    image: postgres:10
    environment:
      - POSTGRES_USER=chesswebmarket
      - POSTGRES_PASSWORD=chessmaster
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - 5300:5432

